app/urls.py
from django.urls import path 
from . import views 
 
app_name = 'app' 
urlpatterns = [
    #Pantalla Principal de la aplicacion
    path('index/', views.index, name='index'),
    #pantallas principales de login
    path('index/registro/', views.registro, name='registro'),
    path('index/profesor/', views.inicioprof, name='profesor'),
    path('index/admin/', views.inicioadmin, name='admin'),
    path('index/estudiante/', views.inicioestudiante, name='Estudiante'),


    # urls admin  ################################################################################################################################
    # Pantalla de Grupo Principal
    path('index/admin/grupos/', views.admingvlg, name='Grupos'),
    # Cuando Selecciona Una Id De Un Grupo Especifico Ejemplo""Cocina"
    path('index/admin/grupos/<int:id>/', views.admingvgga, name='infga'),
    #Agregar Estudiante a Grupos...ER
    path('index/admin/grupos/AE/<int:id>/', views.adminagregarstudiante, name='AgregarEstudiante'),
    #Crear Grupos
    path('index/admin/grupos/crearg', views.admincrearg, name='Crear Grupo'),
    #Editar Grupo
    path('index/admin/grupos/editarg/<int:id>/', views.admineditarg, name='Editar Grupo'),
    #Eliminar Grupo
    path('index/admin/grupos/eliminarg/<int:id>/', views.admineliminarg, name='EliminarGrupo'),
    
    
    #Admin Profesores
    #Pantalla de Profesores Principal
    path('index/admin/profesores/', views.adminpvlp, name='Profesores'),
    #Cuando Selecciona Una Id De un Profesor Especifico Ejemplo "Alexandra Acosta Mendez"
    path('index/admin/profesores/Alexandra', views.adminpvlpa, name='Alexandra'),
    #Crear Profesor
    path('index/admin/profesores/crearp', views.admincrearprofesor, name='Crear Profesor'),
    
    
    #Admin Estudiantes
    #PAntalla De Estudiantes Principal
    path('index/admin/estudiantes/', views.adminevlea, name='Estudiantes'),
    #Crear Estudiante
    path('index/admin/estudiantes/creare', views.admincreare, name='Crear Estudiante'),
    #Editar Estudiante
    path('index/admin/estudiantes/editare<int:id>/', views.admineditare, name='EditarEstudiante'),
    
    # urls profesor ################################################################################################################################
    #Pantalla Principal de Actividades
    path('index/profesor/actividades/', views.profesoractividadp, name='Actividades'),
    #Ver ACtividad especifica en cierto grupo 
    path('index/profesor/actividades/acvidadg', views.profesoravaa, name='Actividades Grupo'),
    #Calificar la actividad
    path('index/profesor/actividades/calificarAc/', views.profesorcalificaractividad, name='calificaractividad'),
    #Crear Actividad
    path('index/profesor/actividades/creara', views.profesorcrearcaractidad, name='Crear Actividad'),
    #Editar Actividad
    path('index/profesor/actividades/editara', views.profesoreditaractividad, name='Editar Actividad'),
    
    #Principal de estudiantes
    path('index/profesor/estudiantes/', views.profesorprincipale, name='Principal Estudiantes'),
    #Cuando seleccione ver un grupo especifico estudiantes de un determinaod grupo "ejemplo 2232377"
    path('index/profesor/estudiantes/2232377', views.profesorgveg, name='2232377'),
    
    #Principal de Grupos
    #Lista Grupos
    path('index/profesor/grupos/', views.profesorgvlg, name='Grupos1'),
    #Lista de grupo especifico por seleccion de id
    path('index/profesor/grupos/1', views.profesorgvggp, name='Grupo 1'),

    #Estudiantes
    #Grupo Principal del estudiante
    path('index/estudiante/grupos', views.estudiantevlge, name='Grupos Estudiante'),
    #estudiante mirando materia 
    path('index/estudiante/grupos/materia', views.estudiantemateria, name='estudiantemateria'),
    
    ]

projnube/urls.py
from django.contrib import admin
from django.urls import path, include
 
urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/templates/app/estudiante/estudiantemateria.html
{% load static %}
<html>
  <head>

    <style>
      .contenido{
      background: rgb(176,191,5);
      background: linear-gradient(0deg, rgba(176,191,5,1) 0%, rgba(2,0,36,1) 9%, rgba(9,9,121,1) 57%, rgba(235,242,244,1) 100%);
      width: 100vw;
      height: 100vh;
      display: grid;
      grid-template: 0.5fr 1fr 1fr / 1fr 1fr 1fr;
      }
      label{
          color:aliceblue;
        }
        a{
          color:rgb(18, 212, 18);
        }
        th{
          background:rgb(165, 87, 87);

          color:rgb(255, 247, 0);
        }
        table{
          background:red;
        }
        tr{
          color:rgb(255, 255, 255);

        }
    </style>

    <title>EstudianteVLGE</title>
    <link rel="stylesheet" href={% static "app/css/Admlista.css" %} />
  </head>
  <body>
    <div class="contenido">
      <div class="imagenatras">
        <div>
          <button class="botonatras">Atras</button>
        </div>
        <img src={% static "app/img/default-user.png" %} alt="userpic" width="100px" />
        <br />
        <h3>
          Estudiante:Pepito Perez
          <br />
          Facultad: Ing. de Telecomunicaciones
        </h3>
      </div>
      <div class="logousta">
        <img src={% static "app/img/SantotoEscudo.png" %} alt="logou" width="100px" />
      </div>

      <div class="tabla">
        <table border="1">
          <label for="Listg" class="titulota">Grupo:</label>
          <label for="Listg" class="titulota">4123</label>
          <label for="Listg" class="titulota">Codigo Estudiante:</label>
          <label for="Listg" class="titulota">2232377:</label>
          <tr>
            <th rowspan="2">Semestre</th>
            <th rowspan="2">Asignatura</th>
            <th rowspan="2">Profesor</th>
            <th colspan="2">Lista de Notas</th>
          </tr>
          <tr>
            <th>Descripcion</th>
            <th>Nota</th>
          </tr>
          <tr>
            <td rowspan="3">5</td>
            <td rowspan="3">Comercio</td>
            <td rowspan="3">Pepio Perez</td>
            <td>Taller</td>
            <td>3.5</td>
          </tr>
          <tr>
            <td>Parcial</td>
            <td>4.0</td>
          </tr>
          <tr>
            <td>Quiz</td>
            <td>1.0</td>
          </tr>
        </table>
      </div>
      <div class="banner">
        <img src={% static "app/img/logo-usta.png" %}  alt="logof" width="500" />
      </div>
      <div class="cerrars">
        <button class="cerrarsesion">Cerrar Sesion</button>
      </div>
    </div>
  </body>
</html>

app/templates/app/estudiante/estudiantes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <style>
      .contenedor{
      background: rgb(176,191,5);
      background: linear-gradient(0deg, rgba(176,191,5,1) 0%, rgba(2,0,36,1) 9%, rgba(9,9,121,1) 57%, rgba(235,242,244,1) 100%);
      width: 100vw;
      height: 100vh;
      display: grid;
      grid-template: 0.5fr 1fr 1fr / 1fr 1fr 1fr;
      }
  
  
        .profesores a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 40px;
          padding: 40px 90px;
          box-shadow: inset 0px 8px 10px rgba(0, 0, 0, 0.25);
        }
        .profesores :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 40px;
          border-top: 3px solid grey;
          padding: 40px 90px;
        }
    </style>

    <link rel="stylesheet" href={% static "app/css/admin.css" %} />
    <title>Estudiantes</title>
  </head>
  <body>
    <div class="contenedor">
      <div class="fotousuario">
        <img src={% static "app/img/default-user.png" %} alt="userpic" width="100px" />
        <br>
        <h3>
            Estudiante:Pepito Perez
            <br>
            Facultad: Ing. de Telecomunicaciones
        </h3>
      </div>
      <div class="logousta">
        <img src={% static "app/img/SantotoEscudo.png" %} alt="logou" width="100px" />
      </div>
      
      <div class="profesores">
          <!-- <button class="botonprofesores">
              Ver lista de grupos
          </button> -->
          <a href="{% url 'app:Grupos Estudiante' %}" class="botonprofesores">Lista de Grupos del Estudiante</a>
      </div>
     
      <div class="banner">
          <img src={% static "app/img/logo-usta.png" %} alt="logof" width="500">
      </div>
      <div class="cerrars">
          <button class="cerrarsesion">
              Cerrar Sesion
          </button>
      </div>
    </div>
  </body>
</html>

app/templates/app/estudiante/estudiantevlge.html
{% load static %}
<html>
  <head>

    <style>
      .contenido{
      background: rgb(176,191,5);
      background: linear-gradient(0deg, rgba(176,191,5,1) 0%, rgba(2,0,36,1) 9%, rgba(9,9,121,1) 57%, rgba(235,242,244,1) 100%);
      width: 100vw;
      height: 100vh;
      display: grid;
      grid-template: 0.5fr 1fr 1fr / 1fr 1fr 1fr;
      }
      label{
          color:aliceblue;
        }
        a{
          color:rgb(18, 212, 18);
        }
        th{
          background:rgb(165, 87, 87);

          color:rgb(255, 247, 0);
        }
        table{
          background:red;
        }
        tr{
          color:rgb(255, 255, 255);

        }
    </style>
    <script src="https://kit.fontawesome.com/96e0ae4487.js" crossorigin="anonymous"></script>
    <title>EstudianteVLGE</title>
    <link rel="stylesheet" href={% static "app/css/Admlista.css" %} />
  </head>
  <body>
    <div class="contenido">
      <div class="imagenatras">
        <div>
          <button class="botonatras">Atras</button>
        </div>
        <img src={% static "app/img/default-user.png" %} alt="userpic" width="100px" />
        <br />
        <h3>
          Estudiante:Pepito Perez
          <br />
          Facultad: Ing. de Telecomunicaciones
        </h3>
      </div>
      <div class="logousta">
        <img src={% static "app/img/SantotoEscudo.png" %} alt="logou" width="100px" />
      </div>

      <div class="tabla">
        <table border="1">
          <label for="Listg" class="titulota">Lista de Grupos</label>
          <tr>
            <th>Semestre</th>
            <th>Id de Grupo</th>
            <th>Asignatura</th>
            <th>Informacion Grupo</th>
          </tr>
          <tr>
              <td rowspan="3">5</td>
              <td>4123</td>
              <td>Comercio</td>
              <td><a href="{% url 'app:estudiantemateria' %}" class="boton5"><i class="fas fa-user-plus"></i></a></td>
          </tr>
          <tr>
              <td>3256</td>
              <td>Mercadeo</td>
              <td><a href="{% url 'app:estudiantemateria' %}" class="boton5"><i class="fas fa-user-plus"></i></a></td>
          </tr>
          <tr>
              <td>4256</td>
              <td>Telematica</td>
              <td><a href="{% url 'app:estudiantemateria' %}" class="boton5"><i class="fas fa-user-plus"></i></a></td>
          </tr>
          <tr>
              <td rowspan="2">6</td>
              <td>6645</td>
              <td>Filosofia</td>
              <td><a href="{% url 'app:estudiantemateria' %}" class="boton5"><i class="fas fa-user-plus"></i></a></td>
          </tr>
          <tr>
              <td>7887</td>
              <td>Fisica Mecanica</td>
              <td><a href="{% url 'app:estudiantemateria' %}" class="boton5"><i class="fas fa-user-plus"></i></a></td>
          </tr>
        </table>
      </div>
      <div class="banner">
        <img src={% static "app/img/logo-usta.png" %}  alt="logof" width="500" />
      </div>
      <div class="cerrars">
        <button class="cerrarsesion">Cerrar Sesion</button>
      </div>
    </div>
  </body>
</html>