app/urls.py
from django.urls import path 
from . import views 
 
app_name = 'app' 
urlpatterns = [
    #Pantalla Principal de la aplicacion
    path('index/', views.index, name='index'),
    #pantallas principales de login
    path('index/registro/', views.registro, name='registro'),
    path('index/profesor/', views.inicioprof, name='profesor'),
    path('index/admin/', views.inicioadmin, name='admin'),
    path('index/estudiante/', views.inicioestudiante, name='Estudiante'),


    # urls admin  ################################################################################################################################
    # Pantalla de Grupo Principal
    path('index/admin/grupos/', views.admingvlg, name='Grupos'),
    # Cuando Selecciona Una Id De Un Grupo Especifico Ejemplo""Cocina"
    path('index/admin/grupos/<int:id>/', views.admingvgga, name='infga'),
    #Agregar Estudiante a Grupos...ER
    path('index/admin/grupos/AE/<int:id>/', views.adminagregarstudiante, name='AgregarEstudiante'),
    #Crear Grupos
    path('index/admin/grupos/crearg', views.admincrearg, name='Crear Grupo'),
    #Editar Grupo
    path('index/admin/grupos/editarg/<int:id>/', views.admineditarg, name='Editar Grupo'),
    #Eliminar Grupo
    path('index/admin/grupos/eliminarg/<int:id>/', views.admineliminarg, name='EliminarGrupo'),
    
    
    #Admin Profesores
    #Pantalla de Profesores Principal
    path('index/admin/profesores/', views.adminpvlp, name='Profesores'),
    #Cuando Selecciona Una Id De un Profesor Especifico Ejemplo "Alexandra Acosta Mendez"
    path('index/admin/profesores/Alexandra', views.adminpvlpa, name='Alexandra'),
    #Crear Profesor
    path('index/admin/profesores/crearp', views.admincrearprofesor, name='Crear Profesor'),
    
    
    #Admin Estudiantes
    #PAntalla De Estudiantes Principal
    path('index/admin/estudiantes/', views.adminevlea, name='Estudiantes'),
    #Crear Estudiante
    path('index/admin/estudiantes/creare', views.admincreare, name='Crear Estudiante'),
    #Editar Estudiante
    path('index/admin/estudiantes/editare<int:id>/', views.admineditare, name='EditarEstudiante'),
    
    # urls profesor ################################################################################################################################
    #Pantalla Principal de Actividades
    path('index/profesor/actividades/', views.profesoractividadp, name='Actividades'),
    #Ver ACtividad especifica en cierto grupo 
    path('index/profesor/actividades/acvidadg', views.profesoravaa, name='Actividades Grupo'),
    #Calificar la actividad
    path('index/profesor/actividades/calificarAc/', views.profesorcalificaractividad, name='calificaractividad'),
    #Crear Actividad
    path('index/profesor/actividades/creara', views.profesorcrearcaractidad, name='Crear Actividad'),
    #Editar Actividad
    path('index/profesor/actividades/editara', views.profesoreditaractividad, name='Editar Actividad'),
    
    #Principal de estudiantes
    path('index/profesor/estudiantes/', views.profesorprincipale, name='Principal Estudiantes'),
    #Cuando seleccione ver un grupo especifico estudiantes de un determinaod grupo "ejemplo 2232377"
    path('index/profesor/estudiantes/2232377', views.profesorgveg, name='2232377'),
    
    #Principal de Grupos
    #Lista Grupos
    path('index/profesor/grupos/', views.profesorgvlg, name='Grupos1'),
    #Lista de grupo especifico por seleccion de id
    path('index/profesor/grupos/1', views.profesorgvggp, name='Grupo 1'),

    #Estudiantes
    #Grupo Principal del estudiante
    path('index/estudiante/grupos', views.estudiantevlge, name='Grupos Estudiante'),
    #estudiante mirando materia 
    path('index/estudiante/grupos/materia', views.estudiantemateria, name='estudiantemateria'),
    
    ]

projnube/urls.py
from django.contrib import admin
from django.urls import path, include
 
urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/templates/app/profesor/profesor.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <style>  
        h3{

          font-size:20px;
        }

        .grupos a{
          color:rgb(255, 255, 255);
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 40px;
          padding: 40px 90px;
          box-shadow: inset 0px 8px 10px rgba(0, 0, 0, 0.25);

        }
        .grupos :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 40px;
          border-top: 3px solid grey;
          padding: 40px 90px;

        }
        .profesores a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 40px;
          padding: 40px 90px;
          box-shadow: inset 0px 8px 10px rgba(0, 0, 0, 0.25);
        }
        .profesores :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 40px;
          border-top: 3px solid grey;
          padding: 40px 90px;
        }
        .estudiantes a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 40px;
          padding: 40px 90px;
          box-shadow: inset 0px 8px 10px rgba(0, 0, 0, 0.25);

        }
        .estudiantes :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 40px;
          border-top: 3px solid grey;
          padding: 40px 90px;
        }
    </style>
    <link rel="stylesheet" href={% static "app/css/admin.css" %} />
    <title>Profesor</title>
  </head>
  <body>
    <div class="contenedor">
      <div class="fotousuario">
        <img src={% static "app/img/default-user.png" %} alt="userpic" width="100px" />
        <br>
        <h3>
            Profesor Pepito Perez
            <br>
            Facultad: Ing. de Telecomunicaciones
        </h3>
      </div>
      <div class="logousta">
        <img src={% static "app/img/SantotoEscudo.png" %} alt="logou" width="100px" />
      </div>
      <div class="grupos">
          <!-- <button class="botongrupos">
              Grupos
          </button> -->
          <a href="{% url 'app:Grupos1' %}" >Grupos</a>
      </div>
      <div class="profesores">
          <!-- <button class="botonprofesores">
              Actividad
          </button> -->
          <a href="{% url 'app:Actividades' %}" >Actividades</a>
      </div>
      <div class="estudiantes">
          <!-- <button class="botonestudiantes">
              Estudiantes
          </button> -->
          <a href="{% url 'app:Principal Estudiantes' %}" >Estudiantes</a>
      </div>
      <div class="banner">
          <img src={% static "app/img/logo-usta.png" %} alt="logof" width="500">
      </div>
      <div class="cerrars">
          <button class="cerrarsesion">
              Cerrar Sesion
          </button>
      </div>
    </div>
  </body>
</html>

app/templates/app/profesor/profesoractividadp.html
{%load static%}
<html>
  <head>
    <style>
      .contenido{
      background: rgb(176,191,5);
      background: linear-gradient(0deg, rgba(176,191,5,1) 0%, rgba(2,0,36,1) 9%, rgba(9,9,121,1) 57%, rgba(235,242,244,1) 100%);
      width: 100vw;
      height: 100vh;
      display: grid;
      grid-template: 0.5fr 1fr 1fr / 1fr 1fr 1fr;
      }
        label{
          color:aliceblue;
        }
        a{
          color:rgb(18, 212, 18);
        }
        th{
          background:rgb(165, 87, 87);

          color:rgb(255, 247, 0);
        }
        table{
          background:red;
        }
        tr{
          color:rgb(255, 255, 255);

        }
       
        .botones001 a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 20px;
          padding: 10px 10px;
        }
        .botones001 :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 20px;
          border-top: 3px solid grey;
        }
        .imagenatras a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 20px;
          padding: 10px 10px;
        }
        .imagenatras :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 20px;
          border-top: 3px solid grey;
        }
    </style>
    <script src="https://kit.fontawesome.com/96e0ae4487.js" crossorigin="anonymous"></script>
    <title>ProfesorActividades</title>
    <link rel="stylesheet" href={% static 'app/css/Admlista.css' %}/>
  </head>
  <body>
    <div class="contenido">
      <div class="imagenatras">
        <div>
          <!-- <button class="botonatras">Atras</button> -->
          <a href="{% url 'app:profesor' %}" class="botonatras" >Atras</a>
        </div>
        <img src={% static "app/img/default-user.png" %} alt="userpic" width="100px" />
        <br />
        <h3>
          Profesor Pepito Perez
          <br />
          Facultad: Ing. de Telecomunicaciones
        </h3>
      </div>
      <div class="botones">
        <div class="botones001">
          <!-- <button class="boton1">Pagina Principal</button> -->
          <a href="{% url 'app:profesor' %}" class="boton1" >Pagina Principal</a>
        </div>
      </div>
      <div class="logousta">
        <img src={% static "app/img/SantotoEscudo.png" %} alt="logou" width="100px" />
      </div>

      <div class="tabla">
        <div class="ttabla">
        </div>
        <table border="1">
          <label for="Listg" class="titulota">Lista de Actividades</label>
          <tr>
            <!--el rowspan es para que llege filas y colspan columnas-->
            <th rowspan="2">Id Actividad</th>
            <th rowspan="2">Descripcion</th>
            <th colspan="7">Grupos</th>
          </tr>
          <tr>
              <th>Codigo del Grupo</th>
              <th>Asignatura del Grupo</th>
              <th>Semestre del Grupo</th>
              <th>Crear Actividad</th>
              <th>Editar Actividad</th>
              <th>Calificar Actividad</th>
              <th>Ver Id de Actividad</th>
          </tr>
          {% for actividades in listaprofesora %}
          <tr>
              <td>{{ actividades.id }}</td>
              <td>{{ actividades.descripcion }}</td>
              <td>{{ actividades.codigodelgrupo }}</td>
              <td>{{ actividades.asignaturadelgrupo }}</td>
              <td>{{ actividades.semestredelgrupo }}</td>
              <td><a href="{% url 'app:Crear Actividad' %}" class="boton2" ><i class="fas fa-plus"></i></a></td>
              <td><a href="{% url 'app:Editar Actividad' %}" class="boton3" ><i class="fas fa-edit"></i></a></td>
              <td><a href="{% url 'app:calificaractividad' %}" class="boton4" ><i class="fas fa-book-open"></i></a></td>
              <td><a href="{% url 'app:Actividades Grupo' %}" class="boton5" ><i class="fas fa-info"></i></a></td>
          </tr>
          {% endfor %}
        </table>
      </div>
      <div class="banner">
        <img src={% static "app/img/logo-usta.png" %} alt="logof" width="500" />
      </div>
      <div class="cerrars">
        <button class="cerrarsesion">Cerrar Sesion</button>
      </div>
    </div>
  </body>
</html>

app/templates/app/profesor/profesoravaa.html
{% load static %}
<html>
  <head>

    <style>
      .contenido{
      background: rgb(176,191,5);
      background: linear-gradient(0deg, rgba(176,191,5,1) 0%, rgba(2,0,36,1) 9%, rgba(9,9,121,1) 57%, rgba(235,242,244,1) 100%);
      width: 100vw;
      height: 100vh;
      display: grid;
      grid-template: 0.5fr 1fr 1fr / 1fr 1fr 1fr;
      }
  
  
        .botones a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 20px;
          padding: 10px 10px;
        }
        .botones :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 20px;
          border-top: 3px solid grey;
        }
        .imagenatras a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 20px;
          padding: 10px 10px;
        }
        .imagenatras :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 20px;
          border-top: 3px solid grey;
        }
        label{
          color:aliceblue;
        }
        a{
          color:rgb(18, 212, 18);
        }
        th{
          background:rgb(165, 87, 87);

          color:rgb(255, 247, 0);
        }
        table{
          background:red;
        }
        tr{
          color:rgb(255, 255, 255);

        }
    </style>





    <title>ProfesorAVAA</title>
    <link rel="stylesheet" href={% static "app/css/Admlista.css" %} />
  </head>
  <body>
    <div class="contenido">
      <div class="imagenatras">
        <div>
          <!-- <button class="botonatras">Atras</button> -->
          <a href="{% url 'app:Actividades' %}" class="botonatras">Atras</a>
        </div>
        <img src={% static "app/img/default-user.png" %} alt="userpic" width="100px" />
        <br />
        <h3>
          Profesor Pepito Perez
          <br />
          Facultad: Ing. de Telecomunicaciones
        </h3>
      </div>
      <div class="botones">
        <div class="botones001">
          <!-- <button class="boton1">Pagina Principal</button> -->
          <a href="{% url 'app:profesor' %}" class="boton1">Pagina Principal</a>
          <!-- <button class="boton2">Crear Actividad</button> -->
          <a href="{% url 'app:Crear Actividad' %}" class="boton2">Crear Actividad</a>
          <!-- <button class="boton3">Editar Actividad</button> -->
          <a href="{% url 'app:Editar Actividad' %}" class="boton3">Editar Actividad</a>
          <!-- <button class="boton4">Calificar Actividad</button> -->
          <a href="{% url 'app:calificaractividad' %}" class="boton4">Calificar Actividad</a>
        </div>
      </div>
      <div class="logousta">
        <img src={% static "app/img/SantotoEscudo.png" %} alt="logou" width="100px" />
      </div>

      <div class="tabla">
        <div class="ttabla">
          <label for="" class="titulo">ID De Actividad:</label>
          <div class="nid">
            <label for="Numero" class="numeroid">1</label>
          </div>
        </div>
        <table border="1">
          <label for="Listg" class="titulota">Lista de Actividades</label>
          <tr>
            <!--el rowspan es para que llege filas y colspan columnas-->
            <th rowspan="2">Id Actividad</th>
            <th colspan="3">Grupos</th>
            <th colspan="3">Lista de Estudiantes</th>
          </tr>
          <tr>
              <th>Codigo del Grupo</th>
              <th>Asignatura del Grupo</th>
              <th>Semestre del Grupo</th>
              <th>Apellidos</th>
              <th>Nombres</th>
              <th>Nota</th>
          </tr>
          <tr>
              <td rowspan="3">1</td>
              <td rowspan="2">214135</td>
              <td rowspan="2">Mercadeo</td>
              <td rowspan="2">6</td>
              <td>Cortazar Guillen</td>
              <td>Alejandro</td>
              <td>4</td>
          </tr>
          <tr>
              <td>Rodriguez Valderrama</td>
              <td>Jair</td>
              <td>3</td>
          </tr>
        </table>
      </div>
      <div class="banner">
        <img src={% static "app/img/logo-usta.png" %}  alt="logof" width="500" />
      </div>
      <div class="cerrars">
        <button class="cerrarsesion">Cerrar Sesion</button>
      </div>
    </div>
  </body>
</html>

app/templates/app/profesor/profesorgveg.html
{% load static %}
<html>
  <head>
    <style>
      .contenido{
      background: rgb(176,191,5);
      background: linear-gradient(0deg, rgba(176,191,5,1) 0%, rgba(2,0,36,1) 9%, rgba(9,9,121,1) 57%, rgba(235,242,244,1) 100%);
      width: 100vw;
      height: 100vh;
      display: grid;
      grid-template: 0.5fr 1fr 1fr / 1fr 1fr 1fr;
      }

      .botones a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 20px;
          padding: 10px 10px;
        }
        .botones :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 20px;
          border-top: 3px solid grey;
        }

        .imagenatras a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 20px;
          padding: 10px 10px;
        }
        .imagenatras :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 20px;
          border-top: 3px solid grey;
        }
        label{
          color:aliceblue;
        }
        a{
          color:rgb(18, 212, 18);
        }
        th{
          background:rgb(165, 87, 87);

          color:rgb(255, 247, 0);
        }
        table{
          background:red;
        }
        tr{
          color:rgb(255, 255, 255);

        }


    </style>
    <title>ProfesorGVEG</title>
    <link rel="stylesheet" href={% static "app/css/Admlista.css" %} />
  </head>
  <body>
    <div class="contenido">
      <div class="imagenatras">
        <div>
          <button class="botonatras">Atras</button>
        </div>
        <img src={% static "app/img/default-user.png" %} alt="userpic" width="100px" />
        <br />
        <h3>
          Profesor Pepito Perez
          <br />
          Facultad: Ing. de Telecomunicaciones
        </h3>
      </div>
      <div class="botones">
        <div class="botones001">
          <!-- <button class="boton1">Pagina Principal</button> -->
          <a href="{% url 'app:profesor' %}" class="boton1">Pagina Principal</a>
        </div>
      </div>
      <div class="logousta">
        <img src={% static "app/img/SantotoEscudo.png" %} alt="logou" width="100px" />
      </div>

      <div class="tabla">
        <div class="ttabla">
          <div>
            <label for="" class="titulo">ID De Grupo:</label>
            <label for="Numero" class="numeroid">1</label>
          </div>
          <div>
            <label for="" class="Idestudiante">ID del Estudiante:</label>
            <label for="Numero" class="numeroid">2232377</label>
          </div>
        </div>
        <table border="1">
          <label for="Listg" class="titulota">Grupo Estudiante</label>
          <tr>
            <!--el rowspan es para que llege filas y colspan columnas-->
            <th rowspan="2">Id Grupo</th>
            <th rowspan="2">Id Estudiante</th>
            <th colspan="3">Lista de Estudiante</th>
            <th colspan="3">Actividades</th>
          </tr>
          <tr>
            <th>Apellidos</th>
            <th>Nombre</th>
            <th>Email</th>
            <th>Numero Actividad</th>
            <th>Descripcion</th>
            <th>Notas</th>
          </tr>
          <tr>
            <td rowspan="3">1</td>
            <td rowspan="3">2232377</td>
            <td rowspan="3">Cortazar Guillen</td>
            <td rowspan="3">Alejandro</td>
            <td rowspan="3">guillencortazaralajandro@gmail.com</td>
            <td>1</td>
            <td>Taller</td>
            <td>3</td>
          </tr>
          <tr>
            <td>2</td>
            <td>Actividad</td>
            <td>4.5</td>
          </tr>
          <tr>
            <td>3</td>
            <td>Parcial</td>
            <td>3.5</td>
          </tr>
        </table>
      </div>
      <div class="banner">
        <img src={% static "app/img/logo-usta.png" %} alt="logof" width="500" />
      </div>
      <div class="cerrars">
        <button class="cerrarsesion">Cerrar Sesion</button>
      </div>
    </div>
  </body>
</html>

app/templates/app/profesor/profesorgvggp.html
{% load static %}
<html>
  <head>

    <style>
      .contenido{
      background: rgb(176,191,5);
      background: linear-gradient(0deg, rgba(176,191,5,1) 0%, rgba(2,0,36,1) 9%, rgba(9,9,121,1) 57%, rgba(235,242,244,1) 100%);
      width: 100vw;
      height: 100vh;
      display: grid;
      grid-template: 0.5fr 1fr 1fr / 1fr 1fr 1fr;
      }
  
  
        .botones a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 20px;
          padding: 10px 10px;
        }
        .botones :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 20px;
          border-top: 3px solid grey;
        }
        label{
          color:aliceblue;
        }
        a{
          color:rgb(18, 212, 18);
        }
        th{
          background:rgb(165, 87, 87);

          color:rgb(255, 247, 0);
        }
        table{
          background:red;
        }
        tr{
          color:rgb(255, 255, 255);

        }
    </style>

    <title>ProfesorGVGGP</title>
    <link rel="stylesheet" href={% static "app/css/Admlista.css" %} />
  </head>
  <body>
    <div class="contenido">
      <div class="imagenatras">
        <div>
          <button class="botonatras">Atras</button>
        </div>
        <img src={% static "app/img/default-user.png" %} alt="userpic" width="100px" />
        <br />
        <h3>
          Profesor Pepito Perez
          <br />
          Facultad: Ing. de Telecomunicaciones
        </h3>
      </div>
      <div class="botones">
        <div class="botones001">
          <!-- <button class="boton1">Pagina Principal</button> -->
          <a href="{% url 'app:profesor' %}" class="boton1">Pagina Principal</a>
        </div>
      </div>
      <div class="logousta">
        <img src={% static "app/img/SantotoEscudo.png" %} alt="logou" width="100px" />
      </div>

      <div class="tabla">
        <div class="ttabla">
          <label for="" class="titulo">ID De Grupo:</label>
          <div class="nid">
            <label for="Numero" class="numeroid">1</label>
          </div>
        </div>
        <table border="1">
          <label for="Listg" class="titulota">Grupo</label>
          <tr>
            <!--el rowspan es para que llege filas y colspan columnas-->
            <th rowspan="2">Id Grupo</th>
            <th rowspan="2">Codigo de Grupos</th>
            <th rowspan="2">Asignatura</th>
            <th rowspan="2">Profesor</th>
            <th colspan="2">Actividades</th>
            <th colspan="3">Lista de Estudiantes</th>
          </tr>
          <tr>
              <th>Numero Actividad</th>
              <th>Descripcion</th>
              <th>Apellidos</th>
              <th>Nombres</th>
              <th>Email</th>
          </tr>
          <tr>
              <td rowspan="3">1</td>
              <td rowspan="3">1213</td>
              <td rowspan="3">Mercadeo</td>
              <td rowspan="3">Pepito Perez</td>
              <td rowspan="2">1</td>
              <td rowspan="2">Taller</td>
              <td>Cortazar Guillen</td>
              <td>Alejandro</td>
              <td>guillencortazaralejandro@gmail.com</td>
          </tr>
          <tr>
              <td>Rodriguez Valderrama</td>
              <td>Jair</td>
              <td>jairrodriguez@usantotomas.edu.co</td>
          </tr>
          <tr>
              <td>2</td>
              <td>Parcial</td>
              <td>Cortazar Guillen</td>
              <td>Alejandro</td>
              <td>guillencortazaralejandro@gmail.com</td>
          </tr>
        </table>
      </div>
      <div class="banner">
        <img src={% static "app/img/logo-usta.png" %} alt="logof" width="500" />
      </div>
      <div class="cerrars">
        <button class="cerrarsesion">Cerrar Sesion</button>
      </div>
    </div>
  </body>
</html>

app/templates/app/profesor/profesorprincipale.html
{% load static %}
<html>
  <head>
    <style>
      .contenido{
      background: rgb(176,191,5);
      background: linear-gradient(0deg, rgba(176,191,5,1) 0%, rgba(2,0,36,1) 9%, rgba(9,9,121,1) 57%, rgba(235,242,244,1) 100%);
      width: 100vw;
      height: 100vh;
      display: grid;
      grid-template: 0.5fr 1fr 1fr / 1fr 1fr 1fr;
      }
  
  
        .botones a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 20px;
          padding: 10px 10px;
        }
        .botones :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 20px;
          border-top: 3px solid grey;
        }
        .imagenatras a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 20px;
          padding: 10px 10px;
        }
        .imagenatras :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 20px;
          border-top: 3px solid grey;
        }

        label{
          color:aliceblue;
        }
        a{
          color:rgb(18, 212, 18);
        }
        th{
          background:rgb(165, 87, 87);

          color:rgb(255, 247, 0);
        }
        table{
          background:red;
        }
        tr{
          color:rgb(255, 255, 255);

        }
    </style>
    <script src="https://kit.fontawesome.com/96e0ae4487.js" crossorigin="anonymous"></script>
    <title>ProfesorGVEG</title>
    <link rel="stylesheet" href={% static "app/css/Admlista.css"%} />
  </head>
  <body>
    <div class="contenido">
      <div class="imagenatras">
        <div>
          <button class="botonatras">Atras</button>
        </div>
        <img src={% static "app/img/default-user.png" %} alt="userpic" width="100px" />
        <br />
        <h3>
          Profesor Pepito Perez
          <br />
          Facultad: Ing. de Telecomunicaciones
        </h3>
      </div>
      <div class="botones">
        <div class="botones001">
          <!-- <button class="boton1">Pagina Principal</button> -->
          <a href="{% url 'app:profesor' %}" class="boton1">Pagina Principal</a>
          <!-- <a href="{% url 'app:2232377' %}" class="boton2">Ver Estudiante por Codigo</a> -->
        </div>
      </div>
      <div class="logousta">
        <img src={% static "app/img/SantotoEscudo.png" %} alt="logou" width="100px" />
      </div>

      <div class="tabla">
        <div class="ttabla">
        </div>
        <table border="1">
          <label for="Listg" class="titulota">Grupo Estudiante</label>
          <tr>
            <!--el rowspan es para que llege filas y colspan columnas-->
            <th rowspan="2">Id Grupo</th>
            <th rowspan="2">Id Estudiante</th>
            <th colspan="4">Lista de Estudiante</th>
          </tr>
          <tr>
            <th>Apellidos</th>
            <th>Nombre</th>
            <th>Email</th>
            <th>Ver Estudiante Grupo</th>
          </tr>
          {% for estudiante in listaprofesore %}
          <tr>
            <td>{{ estudiante.idgrupo }}</td>
            <td>{{ estudiante.idestudiante }}</td>
            <td>{{ estudiante.apellidos }}</td>
            <td>{{ estudiante.nombres }}</td>
            <td>{{ estudiante.email }}</td>
            <td><a href="{% url 'app:2232377' %}" class="boton2"><i class="fas fa-info"></i></a></td>
          </tr>
          {% endfor %}
        </table>
      </div>
      <div class="banner">
        <img src={% static "app/img/logo-usta.png" %} alt="logof" width="500" />
      </div>
      <div class="cerrars">
        <button class="cerrarsesion">Cerrar Sesion</button>
      </div>
    </div>
  </body>
</html>