app/urls.py
from django.urls import path 
from . import views 
 
app_name = 'app' 
urlpatterns = [
    #Pantalla Principal de la aplicacion
    path('index/', views.index, name='index'),
    #pantallas principales de login
    path('index/registro/', views.registro, name='registro'),
    path('index/profesor/', views.inicioprof, name='profesor'),
    path('index/admin/', views.inicioadmin, name='admin'),
    path('index/estudiante/', views.inicioestudiante, name='Estudiante'),


    # urls admin  ################################################################################################################################
    # Pantalla de Grupo Principal
    path('index/admin/grupos/', views.admingvlg, name='Grupos'),
    # Cuando Selecciona Una Id De Un Grupo Especifico Ejemplo""Cocina"
    path('index/admin/grupos/<int:id>/', views.admingvgga, name='infga'),
    #Agregar Estudiante a Grupos...ER
    path('index/admin/grupos/AE/<int:id>/', views.adminagregarstudiante, name='AgregarEstudiante'),
    #Crear Grupos
    path('index/admin/grupos/crearg', views.admincrearg, name='Crear Grupo'),
    #Editar Grupo
    path('index/admin/grupos/editarg/<int:id>/', views.admineditarg, name='Editar Grupo'),
    #Eliminar Grupo
    path('index/admin/grupos/eliminarg/<int:id>/', views.admineliminarg, name='EliminarGrupo'),
    
    
    #Admin Profesores
    #Pantalla de Profesores Principal
    path('index/admin/profesores/', views.adminpvlp, name='Profesores'),
    #Cuando Selecciona Una Id De un Profesor Especifico Ejemplo "Alexandra Acosta Mendez"
    path('index/admin/profesores/Alexandra', views.adminpvlpa, name='Alexandra'),
    #Crear Profesor
    path('index/admin/profesores/crearp', views.admincrearprofesor, name='Crear Profesor'),
    
    
    #Admin Estudiantes
    #PAntalla De Estudiantes Principal
    path('index/admin/estudiantes/', views.adminevlea, name='Estudiantes'),
    #Crear Estudiante
    path('index/admin/estudiantes/creare', views.admincreare, name='Crear Estudiante'),
    #Editar Estudiante
    path('index/admin/estudiantes/editare<int:id>/', views.admineditare, name='EditarEstudiante'),
    
    # urls profesor ################################################################################################################################
    #Pantalla Principal de Actividades
    path('index/profesor/actividades/', views.profesoractividadp, name='Actividades'),
    #Ver ACtividad especifica en cierto grupo 
    path('index/profesor/actividades/acvidadg', views.profesoravaa, name='Actividades Grupo'),
    #Calificar la actividad
    path('index/profesor/actividades/calificarAc/', views.profesorcalificaractividad, name='calificaractividad'),
    #Crear Actividad
    path('index/profesor/actividades/creara', views.profesorcrearcaractidad, name='Crear Actividad'),
    #Editar Actividad
    path('index/profesor/actividades/editara', views.profesoreditaractividad, name='Editar Actividad'),
    
    #Principal de estudiantes
    path('index/profesor/estudiantes/', views.profesorprincipale, name='Principal Estudiantes'),
    #Cuando seleccione ver un grupo especifico estudiantes de un determinaod grupo "ejemplo 2232377"
    path('index/profesor/estudiantes/2232377', views.profesorgveg, name='2232377'),
    
    #Principal de Grupos
    #Lista Grupos
    path('index/profesor/grupos/', views.profesorgvlg, name='Grupos1'),
    #Lista de grupo especifico por seleccion de id
    path('index/profesor/grupos/1', views.profesorgvggp, name='Grupo 1'),

    #Estudiantes
    #Grupo Principal del estudiante
    path('index/estudiante/grupos', views.estudiantevlge, name='Grupos Estudiante'),
    #estudiante mirando materia 
    path('index/estudiante/grupos/materia', views.estudiantemateria, name='estudiantemateria'),
    
    ]

projnube/urls.py
from django.contrib import admin
from django.urls import path, include
 
urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/templates/app/admin/admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <style>
    .contenedor{
    background: rgb(176,191,5);
    background: linear-gradient(0deg, rgba(176,191,5,1) 0%, rgba(2,0,36,1) 9%, rgba(9,9,121,1) 57%, rgba(235,242,244,1) 100%);
    width: 100vw;
    height: 100vh;
    display: grid;
    grid-template: 0.5fr 1fr 1fr / 1fr 1fr 1fr;
    box-shadow: inset 0px 8px 10px rgba(0, 0, 0, 0.25);

    }


      .grupos a{
        color:white;
        display:grid;
        grid-row:2/3;
        text-decoration:none;
        background-color: #549B9E;
        text-align: center;
        font-size: 40px;
        padding: 40px 90px;
        box-shadow: inset 0px 8px 10px rgba(0, 0, 0, 0.25);
      }
      .grupos :hover{
        background-color: #217c80;
        text-align: center;
        font-size: 40px;
          border-top: 3px solid grey;
          padding: 40px 90px;
      }


      .profesores a{
        color:white;
        display:grid;
        grid-row:2/3;
        text-decoration:none;
        background-color: #549B9E;
        text-align: center;
        font-size: 40px;
          padding: 40px 90px;
          box-shadow: inset 0px 8px 10px rgba(0, 0, 0, 0.25);
      }
      .profesores :hover{
        background-color: #217c80;
        text-align: center;
        font-size: 40px;
          border-top: 3px solid grey;
          padding: 40px 90px;
      }


      .estudiantes a{
        color:white;
        display:grid;
        grid-row:2/3;
        text-decoration:none;
        background-color: #549B9E;
        text-align: center;
        font-size: 40px;
          padding: 40px 90px;
          box-shadow: inset 0px 8px 10px rgba(0, 0, 0, 0.25);
      }
      .estudiantes :hover{
        background-color: #196569;
        text-align: center;
        font-size: 40px;
          border-top: 3px solid grey;
          padding: 40px 90px;
      }

    </style>
    <link rel="stylesheet" href={% static 'app/css/admin.css' %}>
    <title>Administracion</title>
  </head>
  <body>
    <div class="contenedor">
      <div class="fotousuario">
        <img src={% static 'app/img/default-user.png' %} alt="userpic" width="100px" />
        <br>
        <h3>
            Administrador:Pepito Perez
        </h3>
      </div>
      <div class="logousta">
        <img src={% static 'app/img/SantotoEscudo.png'  %} alt="logou" width="100px" />
      </div>
      <div class="grupos">
          <!-- <button class="botongrupos">
              Grupos
          </button> -->
          <a href="{% url 'app:Grupos' %}" >Grupos</a>
      </div>
      <div class="profesores">
          <!-- <button class="botonprofesores">
              Profesores
          </button> -->
          <a href="{% url 'app:Profesores' %}" >Profesores</a>
      </div>
      <div class="estudiantes">
          <!-- <button class="botonestudiantes">
              Estudiantes
          </button> -->
          <a href="{% url 'app:Estudiantes' %}" >Estudiantes</a>
      </div>
      <div class="banner">
          <img src={% static 'app/img/logo-usta.png' %} alt="logof" width="500">
      </div>
      <div class="cerrars">
          <button class="cerrarsesion">
              Cerrar Sesion
          </button>
      </div>
    </div>
  </body>
</html>

app/templates/app/admin/adminevlea.html
{% load static %}
<html>
  <head>
    <style>
      .contenido{
    background: rgb(176,191,5);
    background: linear-gradient(0deg, rgba(176,191,5,1) 0%, rgba(2,0,36,1) 9%, rgba(9,9,121,1) 57%, rgba(235,242,244,1) 100%);
    width: 100vw;
    height: 100vh;
    display: grid;
    grid-template: 0.5fr 1fr 1fr / 1fr 1fr 1fr;
    }
    .imagenatras a{
        color:white;
        display:grid;
        grid-row:2/3;
        text-decoration:none;
        background-color: #549B9E;
        text-align: center;
        font-size: 20px;
        padding: 10px 10px;
      }
      .imagenatras :hover{
        background-color: #217c80;
        text-align: center;
        font-size: 20px;
        border-top: 3px solid grey;
      }
      .botones a{
        color:white;
        display:grid;
        grid-row:2/3;
        text-decoration:none;
        background-color: #549B9E;
        text-align: center;
        font-size: 20px;
        padding: 10px 10px;
      }
      .botones :hover{
        background-color: #217c80;
        text-align: center;
        font-size: 20px;
        border-top: 3px solid grey;
      }
      label{
          color:aliceblue;
        }
        a{
          color:rgb(18, 212, 18);
        }
        th{
          background:rgb(165, 87, 87);

          color:rgb(255, 247, 0);
        }
        table{
          background:red;
        }
        tr{
          color:rgb(255, 255, 255);

        }

    </style>
    <title>AdminEVLEA</title>
    <link rel="stylesheet" href={% static "app/css/Admlista.css" %} />
    <script src="https://kit.fontawesome.com/96e0ae4487.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="contenido">
      <div class="imagenatras">
        <div>
          <!-- <button class="botonatras">Atras</button> -->
          <a href="{% url 'app:admin' %}" class="botonatras">Atras</a>
        </div>
        <img src={% static "app/img/default-user.png" %} alt="userpic" width="100px" />
        <br />
        <h3>Administrador:Pepito Perez</h3>
      </div>
      <div class="botones">
        <div class="botones001">
          <!-- <button class="boton1">Crear Estudiante</button> -->
          <a href="{% url 'app:Crear Estudiante' %}" class="boton1">Crear Estudiante</a>
          {% comment %}
          <!-- <button class="boton2">Editar Estudiante</button> -->
          <!-- <a href="{% url 'app:Editar Estudiante' %}" class="boton2">Editar Estudiante</a> -->
          <!-- <button class="boton3">Pagina Principal</button> -->
          {% endcomment %}
          <a href="{% url 'app:admin' %}" class="boton3">Pagina Principal</a>
        </div>
      </div>
      <div class="logousta">
        <img src={% static "app/img/SantotoEscudo.png" %} alt="logou" width="100px" />
      </div>

      <div class="tabla">
        <table border="1">
          <label for="Listg" class="titulota">Estudiantes</label>
          <tr>
            <th>Id</th>
            <th>Codigo</th>
            <th>Apellidos</th>
            <th>Nombres</th>
            <th>Email</th>
            <th>Id Grupos</th>
            <th>Editar Estudiante</th>
          </tr>
          {% for estudiante in listae %}
          <tr>
            <td>{{ estudiante.id }}</td>
            <td>{{ estudiante.codigo }}</td>
            <td>{{ estudiante.apellido }}</td>
            <td>{{ estudiante.nombres }}</td>
            <td>{{ estudiante.email }}</td>
            <td>{{ estudiante.idgrupos }}</td>
            <td><a href="{% url 'app:EditarEstudiante' estudiante.id %}" class="boton2"><i class="fas fa-edit"></i></a></td>
          </tr>
          {% endfor %}
        </table>
      </div>
      <div class="banner">
        <img src={% static "app/img/logo-usta.png" %} alt="logof" width="500" />
      </div>
      <div class="cerrars">
        <button class="cerrarsesion">Cerrar Sesion</button>
      </div>
    </div>
  </body>
</html>

app/templates/app/admin/admingvgga.html
{% load static %}
<html>
  <head>

    <style>
      .contenido{
      background: rgb(176,191,5);
      background: linear-gradient(0deg, rgba(176,191,5,1) 0%, rgba(2,0,36,1) 9%, rgba(9,9,121,1) 57%, rgba(235,242,244,1) 100%);
      width: 100vw;
      height: 100vh;
      display: grid;
      grid-template: 0.5fr 1fr 1fr / 1fr 1fr 1fr;
      }

      .botones a{
        color:white;
        display:grid;
        grid-row:2/3;
        text-decoration:none;
        background-color: #549B9E;
        text-align: center;
        font-size: 20px;
        padding: 10px 10px;
      }
      .botones :hover{
        background-color: #217c80;
        text-align: center;
        font-size: 20px;
        border-top: 3px solid grey;
      }
      label{
          color:aliceblue;
        }
        a{
          color:rgb(18, 212, 18);
        }
        th{
          background:rgb(165, 87, 87);

          color:rgb(255, 247, 0);
        }
        table{
          background:red;
        }
        tr{
          color:rgb(255, 255, 255);

        }
      </style>


    <script src="https://kit.fontawesome.com/96e0ae4487.js" crossorigin="anonymous"></script>
    <title>AdminGVGGA</title>
    <link rel="stylesheet" href={% static "app/css/Admlista.css" %} />
  </head>
  <body>
    <div class="contenido">
      <div class="imagenatras">
        <div>
          <button class="botonatras">Atras</button>
        </div>
        <img src={% static "app/img/default-user.png" %} alt="userpic" width="100px" />
        <br />
        <h3>Administrador:Pepito Perez</h3>
      </div>
      <div class="botones">
        <div class="botones001">
          <!-- <button class="boton1">Crear Grupos</button> -->
          <!-- <button class="boton2">Editar Grupo</button> -->
          <!-- <button class="boton3">Pagina Principal</button> -->
          <a href="{% url 'app:admin' %}" class="boton3">Pagina Principal</a>
          <!-- <button class="boton4">Eliminar Grupo</button> -->
        </div>

        <div class="botones002">
          {% comment %}
          <!-- <button class="boton5">Agregar Estudiante</button> -->
          <!-- <a href="{% url 'app:Agregar Estudiante' %}" class="boton5">Agregar Estudiante</a> -->
          {% endcomment %}
        </div>
      </div>
      <div class="logousta">
        <img src={% static "app/img/SantotoEscudo.png" %} alt="logou" width="100px" />
      </div>

      <div class="tabla">
        <div class="ttabla">
          <label for="" class="titulo">ID De Grupo :</label>
          <div class="nid">
              <label for="Numero" class="numeroid">{{ grupo.id }}</label>
            </div>
        </div>

        <table border="1">
          <label for="Listg" class="titulota">Listas de Grupos</label>
          <tr>
            <th>ID Grupo</th>
            <th>Codigo Grupo</th>
            <th>Asignatura</th>
            <th>Semestre</th>
            <th>Profesor</th>
            <th>Numero Estudiante</th>
            <th>Editar</th>
            <th>Agregar Estudiante</th>
          </tr>
          <tr>
            {% if grupo %}
            <td>{{ grupo.id }}</td>
            <td>{{ grupo.codigogrupo }}</td>
            <td>{{ grupo.asignatura }}</td>
            <td>{{ grupo.semestre }}</td>
            <td>{{ grupo.profesor }}</td>
            <td>{{ grupo.numeroestudiante }}</td>
            <td><a href="{% url 'app:Editar Grupo' grupo.id %}" class="boton2"><i class="fas fa-edit"></i></a></td>
            <td><a href="{% url 'app:AgregarEstudiante' grupo.id %}" class="boton5"><i class="fas fa-user-plus"></i></a></td>
            {% endif %}
          </tr>
        </table>
      </div>
      <div class="banner">
        <img src={% static "app/img/logo-usta.png" %} alt="logof" width="500" />
      </div>
      <div class="cerrars">
        <button class="cerrarsesion">Cerrar Sesion</button>
      </div>
    </div>
  </body>
</html>

app/templates/app/admin/admingvlg.html
{% load static %}
<html>
  <head>
    <style>
      .contenido{
      background: rgb(176,191,5);
      background: linear-gradient(0deg, rgba(176,191,5,1) 0%, rgba(2,0,36,1) 9%, rgba(9,9,121,1) 57%, rgba(235,242,244,1) 100%);
      width: 100vw;
      height: 100vh;
      display: grid;
      grid-template: 0.5fr 1fr 1fr / 1fr 1fr 1fr;
      }
  
  
        .botones a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 20px;
          padding: 10px 10px;
        }
        .botones :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 20px;
          border-top: 3px solid grey;
        }

        .imagenatras a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 20px;
          padding: 10px 10px;
        }
        .imagenatras :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 20px;
          border-top: 3px solid grey;
        }
        label{
          color:aliceblue;
        }
        a{
          color:rgb(18, 212, 18);
        }
        th{
          background:rgb(165, 87, 87);

          color:rgb(255, 247, 0);
        }
        table{
          background:red;
        }
        tr{
          color:rgb(255, 255, 255);

        }
    </style>
    <script src="https://kit.fontawesome.com/96e0ae4487.js" crossorigin="anonymous"></script>





    <title>AdminGVLG</title>
    <link rel="stylesheet" href={% static "app/css/Admlista.css" %} />
  </head>
  <body>
    <div class="contenido">
      <div class="imagenatras">
       <div>
        <!-- <button class="botonatras">Atras</button> -->
        <a href="{% url 'app:admin' %}" class="botonatras">Atras</a>
    </div>
        <img src={% static "app/img/default-user.png" %} alt="userpic" width="100px" />
        <br />
        <h3>Administrador:Pepito Perez</h3>
      </div>
      <div class="botones">
          <div class="botones001">
        <!-- <button class="boton1">Crear Grupos</button> -->
        <a href="{% url 'app:Crear Grupo' %}" class="boton1">Crear Grupo</a>
        {% comment %}
        <!-- <button class="boton2">Editar Grupo</button> -->
      
        <!-- <button class="boton3">Ver Admin G</button> -->
        <!-- <a href="{% url 'app:Cocina' %}" class="boton3">Inf.Grupo</a> -->
        <!-- <button class="boton4">Eliminar Grupo</button> -->
        <!-- <a href="{% url 'app:Eliminar Grupo' %}" class="boton4">Eliminar Grupo</a> -->
        {% endcomment %}
        </div>
        
        <div class="botones002">
        {% comment %}
        <!-- <button class="boton5">Agregar Estudiante</button> -->
        <!-- <a href="{% url 'app:Agregar Estudiante' %}" class="boton5">Agregar Estudiante</a> -->
        <!-- <button class="boton6">Pagina Principal</button> -->
        {% endcomment %}
        <a href="{% url 'app:admin' %}" class="boton6">Pagina Principal</a>
        </div>
      </div>
      <div class="logousta">
        <img src={% static "app/img/SantotoEscudo.png" %} alt="logou" width="100px" />
      </div>

      <div class="tabla">
        <table border="1">
            <label for="Listg"  class="titulota">Listas de Grupos</label>          
          <tr>
            <th>ID Grupo</th>
            <th>Codigo Grupo</th>
            <th>Asignatura</th>
            <th>Semestre</th>
            <th>Profesor</th>
            <th>Numero Estudiante</th>
            <th>Editar</th>
            <th>Inf.Grupo</th>
            <th>Eliminar Grupo</th>
            <th>Agregar Estudiante</th>
          </tr>
          {% for grupo in listag %}
          <tr>
            <td>{{ grupo.id }}</td>
            <td>{{ grupo.codigogrupo }}</td>
            <td>{{ grupo.asignatura }}</td>
            <td>{{ grupo.semestre }}</td>
            <td>{{ grupo.profesor }}</td>
            <td>{{ grupo.numeroestudiante }}</td>
            <td><a href="{% url 'app:Editar Grupo' grupo.id %}" class="boton2"><i class="fas fa-edit"></i></a></td>
            <td><a href="{% url 'app:infga' grupo.id %}" class="boton3"><i class="fas fa-info"></i></a></td>
            <td><a href="{% url 'app:EliminarGrupo' grupo.id %}" class="boton4"><i class="far fa-trash-alt"></i></a></td>
            <td><a href="{% url 'app:AgregarEstudiante' grupo.id %}" class="boton5"><i class="fas fa-user-plus"></i></a></td>
          </tr>
          {% endfor %}
        </table>
      </div>
      <div class="banner">
        <img src={% static "app/img/logo-usta.png" %} alt="logof" width="500" />
      </div>
      <div class="cerrars">
        <button class="cerrarsesion">Cerrar Sesion</button>
      </div>
    </div>
  </body>
</html>

app/templates/app/admin/adminpvlp.html
{% load static %}
<html>
  <head>

    <style>
      .contenido{
      background: rgb(176,191,5);
      background: linear-gradient(0deg, rgba(176,191,5,1) 0%, rgba(2,0,36,1) 9%, rgba(9,9,121,1) 57%, rgba(235,242,244,1) 100%);
      width: 100vw;
      height: 100vh;
      display: grid;
      grid-template: 0.5fr 1fr 1fr / 1fr 1fr 1fr;
      }
      
  
        .imagenatras a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 20px;
          padding: 10px 10px;
        }
        .imagenatras :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 20px;
          border-top: 3px solid grey;
        }
        .botones a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 20px;
          padding: 10px 10px;
        }
        .botones :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 20px;
          border-top: 3px solid grey;
        }
        label{
          color:aliceblue;
        }
        a{
          color:rgb(18, 212, 18);
        }
        th{
          background:rgb(165, 87, 87);

          color:rgb(255, 247, 0);
        }
        table{
          background:red;
        }
        tr{
          color:rgb(255, 255, 255);

        }
    </style>



     <script src="https://kit.fontawesome.com/96e0ae4487.js" crossorigin="anonymous"></script>
    <title>AdminPVLP</title>
    <link rel="stylesheet" href={% static "app/css/Admlista.css" %} />
  </head>
  <body>
    <div class="contenido">
      <div class="imagenatras">
        <div>
          <!-- <button class="botonatras">Atras</button> -->
          <a href="{% url 'app:admin' %}" class="botonatras">Atras</a>
        </div>
        <img src={% static "app/img/default-user.png" %} alt="userpic" width="100px" />
        <br />
        <h3>Administrador:Pepito Perez</h3>
      </div>
      <div class="botones">
        <div class="botones001">
          <!-- <button class="boton1">Crear Profesor</button> -->
          <a href="{% url 'app:Crear Profesor' %}" class="boton1">Crear Profesor</a>
          <!-- <button class="boton2">Ver Lista P</button> -->
          <!-- <a href="{% url 'app:Alexandra' %}" class="boton2">Ver Lista P.</a> -->
          <!-- <button class="boton3">Pagina Principal</button> -->
          <a href="{% url 'app:admin' %}" class="boton3">Pagina Principal</a>
        </div>
      </div>
      <div class="logousta">
        <img src={% static "app/img/SantotoEscudo.png" %} alt="logou" width="100px" />
      </div>

      <div class="tabla">
        <table border="1">
          <label for="Listg" class="titulota">Profesores</label>
          <tr>
            <th>Apeliidos</th>
            <th>Nombres</th>
            <th>Email</th>
            <th>Id Grupos</th>
            <th>Ver Lista P</th>

          </tr>
          {% for profesor in listap %}
          <tr>
            <td >{{ profesor.apellido }}</td>
            <td >{{ profesor.nombres }}</td>
            <td >{{ profesor.email }}</td>
            <td >{{ profesor.idgrupos }}</td>
            <td ><a href="{% url 'app:Alexandra' %}" class="boton2"><i class="fas fa-info"></i></a></td>
          </tr>
          {% endfor %}
        </table>
      </div>
      <div class="banner">
        <img src={% static "app/img/logo-usta.png" %} alt="logof" width="500" />
      </div>
      <div class="cerrars">
        <button class="cerrarsesion">Cerrar Sesion</button>
      </div>
    </div>
  </body>
</html>

app/templates/app/admin/adminpvlpa.html
{% load static %}
<html>
  <head>
    <style>
      .contenido{
      background: rgb(176,191,5);
      background: linear-gradient(0deg, rgba(176,191,5,1) 0%, rgba(2,0,36,1) 9%, rgba(9,9,121,1) 57%, rgba(235,242,244,1) 100%);
      width: 100vw;
      height: 100vh;
      display: grid;
      grid-template: 0.5fr 1fr 1fr / 1fr 1fr 1fr;
      }
  
        .botones a{
          color:white;
          display:grid;
          grid-row:2/3;
          text-decoration:none;
          background-color: #549B9E;
          text-align: center;
          font-size: 20px;
          padding: 10px 10px;
        }
        .botones :hover{
          background-color: #217c80;
          text-align: center;
          font-size: 20px;
          border-top: 3px solid grey;
        }
        label{
          color:aliceblue;
        }
        a{
          color:rgb(18, 212, 18);
        }
        th{
          background:rgb(165, 87, 87);

          color:rgb(255, 247, 0);
        }
        table{
          background:red;
        }
        tr{
          color:rgb(255, 255, 255);

        }
    </style>
    <title>AdminPVLPA</title>
    <link rel="stylesheet" href={% static "app/css/Admlista.css" %} />
  </head>
  <body>
    <div class="contenido">
      <div class="imagenatras">
        <div>
          <button class="botonatras">Atras</button>
        </div>
        <img src={% static "app/img/default-user.png" %} alt="userpic" width="100px" />
        <br />
        <h3>Administrador:Pepito Perez</h3>
      </div>
      <div class="botones">
        <div class="botones001">
          <!-- <button class="boton1">Crear Profesor</button> -->
          <a href="{% url 'app:Crear Profesor' %}" class="boton1">Crear Profesor</a>
          <!-- <button class="boton3">Pagina Principal</button> -->
          <a href="{% url 'app:admin' %}" class="boton3">Pagina Principal</a>
        </div>
      </div>
      <div class="logousta">
        <img src={% static "app/img/SantotoEscudo.png" %} alt="logou" width="100px" />
      </div>

      <div class="tabla">
        <div class="ttabla">
            <label for="" class="titulo">ID De Grupo :</label>
            <div class="nid">
                <label for="Numero" class="numeroid">1</label>
              </div>
          </div>
        <table border="1">
          <label for="Listg" class="titulota">Profesores</label>
          <tr>
              <!--el rowspan es para que llege filas y colspan columnas-->
            <th rowspan="2">Id Grupo</th>
            <th rowspan="2">Apellidos</th>
            <th rowspan="2">Nombres</th>
            <th rowspan="2">Email</th>
            <th colspan="4">Lista de Cursos</th>
          </tr>
          <tr>
            <th>Semestre</th>
            <th>Codigo</th>
            <th>Asignatura</th>
            <th>Cantidad de Estudiante</th>
          </tr>
          <tr>
              <td rowspan="3">1</td>
              <td rowspan="3">Acosta Mendez</td>
              <td rowspan="3">Alexandra</td>
              <td rowspan="3">alexandrac@gmail.com</td>
              <td>2</td>
              <td>21445</td>
              <td>Cocina</td>
              <td>4</td>
          </tr>
          <tr>
              <td>4</td>
              <td>12356</td>
              <td>Fisica</td>
              <td>12</td>
          </tr>
          <tr>
              <td>6</td>
              <td>12468</td>
              <td>Diseño y Corte de Metales</td>
              <td>30</td>
          </tr>
        </table>
      </div>
      <div class="banner">
        <img src={% static "app/img/logo-usta.png" %} alt="logof" width="500" />
      </div>
      <div class="cerrars">
        <button class="cerrarsesion">Cerrar Sesion</button>
      </div>
    </div>
  </body>
</html>