app/urls.py
from django.urls import path 
from . import views 
 
app_name = 'app' 
urlpatterns = [
    #Pantalla Principal de la aplicacion
    path('index/', views.index, name='index'),
    #pantallas principales de login
    path('index/registro/', views.registro, name='registro'),
    path('index/profesor/', views.inicioprof, name='profesor'),
    path('index/admin/', views.inicioadmin, name='admin'),
    path('index/estudiante/', views.inicioestudiante, name='Estudiante'),


    # urls admin  ################################################################################################################################
    # Pantalla de Grupo Principal
    path('index/admin/grupos/', views.admingvlg, name='Grupos'),
    # Cuando Selecciona Una Id De Un Grupo Especifico Ejemplo""Cocina"
    path('index/admin/grupos/<int:id>/', views.admingvgga, name='infga'),
    #Agregar Estudiante a Grupos...ER
    path('index/admin/grupos/AE/<int:id>/', views.adminagregarstudiante, name='AgregarEstudiante'),
    #Crear Grupos
    path('index/admin/grupos/crearg', views.admincrearg, name='Crear Grupo'),
    #Editar Grupo
    path('index/admin/grupos/editarg/<int:id>/', views.admineditarg, name='Editar Grupo'),
    #Eliminar Grupo
    path('index/admin/grupos/eliminarg/<int:id>/', views.admineliminarg, name='EliminarGrupo'),
    
    
    #Admin Profesores
    #Pantalla de Profesores Principal
    path('index/admin/profesores/', views.adminpvlp, name='Profesores'),
    #Cuando Selecciona Una Id De un Profesor Especifico Ejemplo "Alexandra Acosta Mendez"
    path('index/admin/profesores/Alexandra', views.adminpvlpa, name='Alexandra'),
    #Crear Profesor
    path('index/admin/profesores/crearp', views.admincrearprofesor, name='Crear Profesor'),
    
    
    #Admin Estudiantes
    #PAntalla De Estudiantes Principal
    path('index/admin/estudiantes/', views.adminevlea, name='Estudiantes'),
    #Crear Estudiante
    path('index/admin/estudiantes/creare', views.admincreare, name='Crear Estudiante'),
    #Editar Estudiante
    path('index/admin/estudiantes/editare<int:id>/', views.admineditare, name='EditarEstudiante'),
    
    # urls profesor ################################################################################################################################
    #Pantalla Principal de Actividades
    path('index/profesor/actividades/', views.profesoractividadp, name='Actividades'),
    #Ver ACtividad especifica en cierto grupo 
    path('index/profesor/actividades/acvidadg', views.profesoravaa, name='Actividades Grupo'),
    #Calificar la actividad
    path('index/profesor/actividades/calificarAc/', views.profesorcalificaractividad, name='calificaractividad'),
    #Crear Actividad
    path('index/profesor/actividades/creara', views.profesorcrearcaractidad, name='Crear Actividad'),
    #Editar Actividad
    path('index/profesor/actividades/editara', views.profesoreditaractividad, name='Editar Actividad'),
    
    #Principal de estudiantes
    path('index/profesor/estudiantes/', views.profesorprincipale, name='Principal Estudiantes'),
    #Cuando seleccione ver un grupo especifico estudiantes de un determinaod grupo "ejemplo 2232377"
    path('index/profesor/estudiantes/2232377', views.profesorgveg, name='2232377'),
    
    #Principal de Grupos
    #Lista Grupos
    path('index/profesor/grupos/', views.profesorgvlg, name='Grupos1'),
    #Lista de grupo especifico por seleccion de id
    path('index/profesor/grupos/1', views.profesorgvggp, name='Grupo 1'),

    #Estudiantes
    #Grupo Principal del estudiante
    path('index/estudiante/grupos', views.estudiantevlge, name='Grupos Estudiante'),
    #estudiante mirando materia 
    path('index/estudiante/grupos/materia', views.estudiantemateria, name='estudiantemateria'),
    
    ]

projnube/urls.py
from django.contrib import admin
from django.urls import path, include
 
urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/templates/app/index.html
{% load static %}
<html
lang="esp">
  <head>
    <style>
      .usuario {
        grid-row:2/3;
        color:rgb(233, 222, 76);
        text-align: center;
      }
      .contraseña {
        grid-row:2/3;
        color:rgb(255, 238, 0);

      }

    .cajau {
      color:rgb(0, 0, 0);
        display:grid;
        grid-row:2/3;
        text-decoration:none;
        background-color: #ffffff;
        text-align: center;
        font-size: 20px;
        padding: 10px 10px;
        box-shadow: inset 0px 8px 8px rgba(0, 0, 0, 0.25);

    }
    
    .input {
      color:white;
        display:grid;
        grid-row:2/3;
        text-decoration:none;
        background-color: #4c41ec;
        text-align: center;
        font-size: 20px;
        padding: 20px 20px;
        box-shadow: inset 0px 8px 8px rgba(0, 0, 0, 0.25);

    }   
    .cajac {
      color:rgb(0, 0, 0);
        display:grid;
        grid-row:2/3;
        text-decoration:none;
        background-color: #dde7e8;
        text-align: center;
        font-size: 20px;
        padding: 10px 40px;
        box-shadow: inset 0px 8px 8px rgba(0, 0, 0, 0.25);
      


      box-shadow: inset 0px 8px 8px rgba(0, 0, 0, 0.25);

      } 

    .contenedor{
    background: rgb(176,191,5);
    background: linear-gradient(0deg, rgba(176,191,5,1) 0%, rgba(2,0,36,1) 9%, rgba(9,9,121,1) 57%, rgba(235,242,244,1) 100%);
    width: 100vw;
    height: 100vh;
    display: grid;
    grid-template: 0.5fr 1fr 1fr / 1fr 1fr 1fr;
    box-shadow: inset 0px 25px 8px rgba(0, 0, 0, 0.25);

    }


      .breg a{
      color:white;
        display:grid;
        grid-row:2/3;
        text-decoration:none;
        background-color: #549B9E;
        text-align: center;
        font-size: 20px;
        padding: 10px 10px;
        box-shadow: inset 0px 8px 8px rgba(0, 0, 0, 0.25);

      }
      .breg :hover{
        background-color: #217c80;
        text-align: center;
        font-size: 20px;
        border-top: 3px solid grey;
      }  
      .input a{
      color:white;
        display:grid;
        grid-row:2/3;
        text-decoration:none;
        background-color: #549B9E;
        text-align: center;
        font-size: 20px;
        padding: 10px 10px;
      }
      .input :hover{
        background-color: #217c80;
        text-align: center;
        font-size: 20px;
        border-top: 3px solid grey;
        padding: 20px 20px; 

      }  


      .tronco1{

        padding: 10px 30px;

      }
    </style>
    <meta charset="UTF-8">
    <title>Pagina Principal</title>
    <link rel="stylesheet" href= {% static 'app/css/principal.css' %}  />
  </head>
  <body>
    <div class="contenedor">
      <!--Titulo principal y logo USTA-->
      <div class="cabeza">
        <div class="logo">
          <img src={% static "app/img/logo-usta.png" %} alt="logo" width="300px" />
        </div>
      </div>
      <!--Nombre de usuario y contraseña-->
      <div class="tronco1">
        <div class="usauriop">
          <label for="usuario" class="usuario">Usuario</label>
          <input class="cajau type="text" id="usuario" placeholder="Digite el
          nombre de usuario" size="51"/>
          <br />
          <br />
          <label for="contraseña" class="contraseña">Contraseña</label>
          <input type="password" class="cajac" size="46" />
        </div class="iniciar">
        <!--Boton de inicio de sesión y registro-->
        <input class=input type="submit" value="Iniciar Sesion" class="botoninicio" />
        <div class="breg">
          <a href="{% url 'app:registro' %}" >Registrarse</a>
        </div>
        <div class="breg"><a href="{% url 'app:admin' %}" >Admin</a></div>
        <div class="breg"><a href="{% url 'app:profesor' %}" >Profesor</a></div>
        <div class="breg"><a href="{% url 'app:Estudiante' %}" >Estudiante</a></div>

        
       <!-- <button class="botonregistro">Registrarse</button> -->

      </div>
      <div class="finalp"></div>
    </div>
  </body>
</html>